import Foundation
import Testing

@testable import Authentication

private func date(_ unix: Double) -> Date {
  Date(timeIntervalSince1970: unix)
}

/// The secret platform-go's `totp` tests use verbatim. The expected codes below were generated by the
/// **actual** `github.com/pquerna/otp` library (the Go origin's dependency) at fixed timestamps, so a
/// match here proves the Swift port is wire-compatible with the Go side for the same secret + time.
private let exampleSecret = "HEREISASECRETWHICHIVEMADEUPBECAUSEIWANNATESTRELIABLY"

@Suite("TOTP generation — Go/pquerna parity vectors")
struct TOTPGoParityTests {
  private let totp = TOTP()  // defaults: period 30, 6 digits, SHA-1, skew 1 (Go's shortcut config)

  @Test(
    "codes match the pquerna library for the platform-go example secret",
    arguments: [
      (0.0, "624865"),
      (59.0, "565579"),
      (1_111_111_109.0, "718722"),
      (1_234_567_890.0, "586525"),
      (2_000_000_000.0, "789925"),
      (1_751_673_600.0, "844456"),
    ])
  func exampleSecretVectors(unix: Double, expected: String) throws {
    #expect(try totp.generate(secret: exampleSecret, at: date(unix)) == expected)
  }
}

/// Canonical RFC 6238 Appendix B test vectors (truncated to 6 digits), an origin-independent check that
/// the RFC 4226 dynamic-truncation math is correct across all three hash functions.
@Suite("TOTP generation — RFC 6238 Appendix B")
struct TOTPRFCVectorTests {
  // base32("12345678901234567890") — the RFC's 20-byte ASCII SHA-1 seed.
  private let sha1Secret = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ"

  @Test(
    "SHA-1 vectors",
    arguments: [
      (59.0, "287082"),
      (1_111_111_109.0, "081804"),
      (1_111_111_111.0, "050471"),
      (1_234_567_890.0, "005924"),
      (2_000_000_000.0, "279037"),
      (20_000_000_000.0, "353130"),
    ])
  func sha1(unix: Double, expected: String) throws {
    let totp = TOTP(algorithm: .sha1)
    #expect(try totp.generate(secret: sha1Secret, at: date(unix)) == expected)
  }

  @Test("SHA-256 vector at T=59")
  func sha256() throws {
    // base32("12345678901234567890123456789012") — the RFC's 32-byte SHA-256 seed.
    let secret = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQGEZA===="
    let totp = TOTP(algorithm: .sha256)
    #expect(try totp.generate(secret: secret, at: date(59)) == "119246")
  }

  @Test("SHA-512 vector at T=59")
  func sha512() throws {
    // base32 of the RFC's 64-byte SHA-512 seed.
    let secret =
      "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQGEZDGNA="
    let totp = TOTP(algorithm: .sha512)
    #expect(try totp.generate(secret: secret, at: date(59)) == "693936")
  }

  @Test("8-digit SHA-1 vector at T=59")
  func eightDigits() throws {
    let totp = TOTP(digits: 8, algorithm: .sha1)
    #expect(try totp.generate(secret: sha1Secret, at: date(59)) == "94287082")
  }
}

@Suite("TOTP verification")
struct TOTPVerificationTests {
  private let totp = TOTP()

  @Test("a freshly generated code verifies at the same instant")
  func happyPath() throws {
    let now = date(1_751_673_600)
    let code = try totp.generate(secret: exampleSecret, at: now)
    #expect(throws: Never.self) {
      try totp.verify(code: code, secret: exampleSecret, at: now)
    }
    #expect(try totp.isValid(code: code, secret: exampleSecret, at: now))
  }

  @Test("empty code throws codeRequired")
  func emptyCode() {
    #expect(throws: TOTPError.codeRequired) {
      try totp.verify(code: "", secret: exampleSecret, at: date(59))
    }
  }

  @Test("wrong code throws invalidCode")
  func wrongCode() {
    #expect(throws: TOTPError.invalidCode) {
      try totp.verify(code: "000000", secret: exampleSecret, at: date(59))
    }
  }

  @Test("a wrong-length code is invalid, not codeRequired")
  func wrongLength() throws {
    #expect(throws: TOTPError.invalidCode) {
      try totp.verify(code: "12345", secret: exampleSecret, at: date(59))
    }
    #expect(try totp.isValid(code: "1234567", secret: exampleSecret, at: date(59)) == false)
  }

  @Test("a malformed base32 secret throws invalidSecret")
  func badSecret() {
    // '1', '8', '9', '0' are outside the RFC 4648 base32 alphabet.
    #expect(throws: TOTPError.invalidSecret) {
      try totp.verify(code: "123456", secret: "SECRET189", at: date(59))
    }
    #expect(throws: TOTPError.invalidSecret) {
      _ = try totp.generate(secret: "SECRET189", at: date(59))
    }
  }

  @Test("skew accepts an adjacent window and rejects one two periods away")
  func skewWindow() throws {
    // Generate for window 0 (t=0), then verify from within neighbouring windows.
    let code = try totp.generate(secret: exampleSecret, at: date(0))

    // One period later (window 1) still validates: its scan includes window 0.
    #expect(try totp.isValid(code: code, secret: exampleSecret, at: date(30)))
    // One period earlier is symmetric.
    #expect(try totp.isValid(code: code, secret: exampleSecret, at: date(29)))
    // Two periods away (window 2) is outside the ±1 skew — no match.
    #expect(try totp.isValid(code: code, secret: exampleSecret, at: date(60)) == false)
  }

  @Test("skew 0 accepts only the exact window")
  func noSkew() throws {
    let strict = TOTP(skew: 0)
    let code = try strict.generate(secret: exampleSecret, at: date(0))
    #expect(try strict.isValid(code: code, secret: exampleSecret, at: date(15)))
    #expect(try strict.isValid(code: code, secret: exampleSecret, at: date(30)) == false)
  }
}

@Suite("Base32 decoding")
struct Base32Tests {
  @Test("tolerates missing padding, lower-case, and surrounding whitespace (pquerna normalization)")
  func normalization() {
    // "MZXW6===" is base32("foo"); the padded, unpadded, lower-case, and space-wrapped forms all decode
    // to the same bytes.
    let expected = Data("foo".utf8)
    #expect(Base32.decode("MZXW6===") == expected)
    #expect(Base32.decode("MZXW6") == expected)
    #expect(Base32.decode("mzxw6") == expected)
    #expect(Base32.decode("  MZXW6  ") == expected)
  }

  @Test("rejects characters outside the alphabet")
  func rejectsInvalid() {
    #expect(Base32.decode("0189") == nil)  // digits absent from the base32 alphabet
    #expect(Base32.decode("MZX W6") == nil)  // internal whitespace is invalid, as in Go
  }
}
